"""test13

Revision ID: 121a8e9240e9
Revises: 4688621383a3
Create Date: 2025-03-13 11:31:39.559864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121a8e9240e9'
down_revision: Union[str, None] = '4688621383a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userss', 'warning_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('warning_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
