"""test17

Revision ID: 202cf60e660b
Revises: 36c97c5eb44c
Create Date: 2025-03-17 14:44:03.090582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202cf60e660b'
down_revision: Union[str, None] = '36c97c5eb44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('userss', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('userss', 'password')
    # ### end Alembic commands ###
