"""test8

Revision ID: 2dc0470c0fc8
Revises: 6f2e0c91dd0e
Create Date: 2025-03-10 15:13:52.217432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dc0470c0fc8"
down_revision: Union[str, None] = "6f2e0c91dd0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fillbottle")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fillbottle",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("is_filled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("drank", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("bottle_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["bottle_id"], ["bottles.id"], name="fillbottle_bottle_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="fillbottle_pkey"),
        sa.UniqueConstraint("bottle_id", name="fillbottle_bottle_id_key"),
    )
    # ### end Alembic commands ###
