"""initial

Revision ID: 3f1c03798fa4
Revises: 
Create Date: 2025-03-06 14:38:11.292900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f1c03798fa4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_shortner')
    op.drop_table('customer')
    op.drop_table('sales')
    op.create_foreign_key(None, 'bottles', 'userss', ['user_id'], ['id'])
    op.drop_constraint('userss_bottle_id_fkey', 'userss', type_='foreignkey')
    op.drop_column('userss', 'bottle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('bottle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('userss_bottle_id_fkey', 'userss', 'bottles', ['bottle_id'], ['id'])
    op.drop_constraint(None, 'bottles', type_='foreignkey')
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notification', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sales_pkey')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='customer_pkey')
    )
    op.create_table('url_shortner',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('long_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'short_url', name='url_shortner_pkey'),
    sa.UniqueConstraint('short_url', name='url_shortner_short_url_key')
    )
    # ### end Alembic commands ###
