"""test12

Revision ID: 4688621383a3
Revises: 0897c44a365c
Create Date: 2025-03-12 22:16:14.283960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4688621383a3'
down_revision: Union[str, None] = '0897c44a365c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('reminder_count', sa.Integer(), nullable=True))
    op.add_column('userss', sa.Column('warning_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userss', 'warning_sent')
    op.drop_column('userss', 'reminder_count')
    # ### end Alembic commands ###
