"""test15

Revision ID: 50a2661f102d
Revises: c60be3da46eb
Create Date: 2025-03-13 16:43:05.946668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a2661f102d'
down_revision: Union[str, None] = 'c60be3da46eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userss', 'reminder_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('reminder_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
