"""test19

Revision ID: 5a7410691d25
Revises: a5bb5336eacb
Create Date: 2025-03-17 16:26:01.136737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7410691d25'
down_revision: Union[str, None] = 'a5bb5336eacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('total_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bottles', 'total_amount')
    # ### end Alembic commands ###
