"""test7

Revision ID: 6f2e0c91dd0e
Revises: 8d68da2d83c1
Create Date: 2025-03-10 12:13:26.452346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2e0c91dd0e'
down_revision: Union[str, None] = '8d68da2d83c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bottles_email_id_key', 'bottles', type_='unique')
    op.drop_column('bottles', 'password')
    op.drop_column('bottles', 'email_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('email_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bottles', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('bottles_email_id_key', 'bottles', ['email_id'])
    # ### end Alembic commands ###
