"""test18

Revision ID: a5bb5336eacb
Revises: 202cf60e660b
Create Date: 2025-03-17 16:16:28.685836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bb5336eacb'
down_revision: Union[str, None] = '202cf60e660b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('last_drink_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bottles', 'last_drink_time')
    # ### end Alembic commands ###
