"""test10

Revision ID: c2ef36ce4e16
Revises: 2ed8b9f60104
Create Date: 2025-03-11 12:04:10.584881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2ef36ce4e16"
down_revision: Union[str, None] = "2ed8b9f60104"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userss", sa.Column("last_drink_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userss", "last_drink_time")
    # ### end Alembic commands ###
